### ISSUE TITLE
commit-email.rb failed some cases

### ISSUE THREAD

**Issue by hsbt** [ruby/git.ruby-lang.org#82]
```
Encoding::CompatibilityError: invalid byte sequence in US-ASCII
/home/git/git.ruby-lang.org/bin/commit-email.rb:124:in `strip'
/home/git/git.ruby-lang.org/bin/commit-email.rb:124:in `git_show'
/home/git/git.ruby-lang.org/bin/commit-email.rb:31:in `build'
/home/git/git.ruby-lang.org/bin/commit-email.rb:186:in `block (2 levels) in main'
/home/git/git.ruby-lang.org/bin/commit-email.rb:185:in `map'
/home/git/git.ruby-lang.org/bin/commit-email.rb:185:in `block in main'
/home/git/git.ruby-lang.org/bin/commit-email.rb:183:in `each'
/home/git/git.ruby-lang.org/bin/commit-email.rb:183:in `each_slice'
/home/git/git.ruby-lang.org/bin/commit-email.rb:183:in `each'
/home/git/git.ruby-lang.org/bin/commit-email.rb:183:in `flat_map'
/home/git/git.ruby-lang.org/bin/commit-email.rb:183:in `main'
/home/git/git.ruby-lang.org/bin/commit-email.rb:383:in `<main>'
/home/git/git.ruby-lang.org/bin/commit-email.rb:200:in `popen': no implicit conversion of nil into String (TypeError)

    IO.popen([SENDMAIL, to], 'w') do |f|
             ^^^^^^^^^^^^^^^^^^^
        from /home/git/git.ruby-lang.org/bin/commit-email.rb:200:in `sendmail'
        from /home/git/git.ruby-lang.org/bin/commit-email.rb:390:in `rescue in <main>'
        from /home/git/git.ruby-lang.org/bin/commit-email.rb:382:in `<main>'
/home/git/git.ruby-lang.org/bin/commit-email.rb:124:in `strip': invalid byte sequence in US-ASCII (Encoding::CompatibilityError)
        from /home/git/git.ruby-lang.org/bin/commit-email.rb:124:in `git_show'
        from /home/git/git.ruby-lang.org/bin/commit-email.rb:31:in `build'
        from /home/git/git.ruby-lang.org/bin/commit-email.rb:186:in `block (2 levels) in main'
        from /home/git/git.ruby-lang.org/bin/commit-email.rb:185:in `map'
        from /home/git/git.ruby-lang.org/bin/commit-email.rb:185:in `block in main'
        from /home/git/git.ruby-lang.org/bin/commit-email.rb:183:in `each'
        from /home/git/git.ruby-lang.org/bin/commit-email.rb:183:in `each_slice'
        from /home/git/git.ruby-lang.org/bin/commit-email.rb:183:in `each'
        from /home/git/git.ruby-lang.org/bin/commit-email.rb:183:in `flat_map'
        from /home/git/git.ruby-lang.org/bin/commit-email.rb:183:in `main'
        from /home/git/git.ruby-lang.org/bin/commit-email.rb:383:in `<main>'
```

Failed payload is here:

```
{"attachments":[
{"title":"8e73609c7b (master): [rubygems/rubygems] Fix weirdness of \"interrupt\" test command","title_link":"https://github.com/ruby/ruby/commit/8e73609c7b4c7fdc35e47cefd8f696777c0da5e6","text":"https://github.com/rubygems/rubygems/commit/0a75590ac9","footer":"Hiroshi SHIBATA","footer_icon":"https://www.gravatar.com/avatar/f2748d34b03ed11330f2a2218904eb2d","ts":1727847294,"color":"#24282D"},
{"title":"3d1eb62bf3 (master): [rubygems/rubygems] Standarize \"ins\" test command too","title_link":"https://github.com/ruby/ruby/commit/3d1eb62bf38e6d6691213018ef29a5680f9d2161","text":"https://github.com/rubygems/rubygems/commit/517e9a8669","footer":"Hiroshi SHIBATA","footer_icon":"https://www.gravatar.com/avatar/f2748d34b03ed11330f2a2218904eb2d","ts":1727847294,"color":"#24282D"},
{"title":"02d50d9cb1 (master): [rubygems/rubygems] Simplify command loading","title_link":"https://github.com/ruby/ruby/commit/02d50d9cb17e8daccf788347593e97cae354ba4e","text":"https://github.com/rubygems/rubygems/commit/95f60f0e60","footer":"Hiroshi SHIBATA","footer_icon":"https://www.gravatar.com/avatar/f2748d34b03ed11330f2a2218904eb2d","ts":1727847294,"color":"#24282D"},
{"title":"49483904d8 (master): [rubygems/rubygems] Make sure MissingSpecVersionError#to_s prints exception message","title_link":"https://github.com/ruby/ruby/commit/49483904d8fcac3bd5ef9e897279563235583f4a","text":"Gem command loading errors rely on `#to_s` on the raised exception, but\nin the case of `MissingSpecVersionError` that was only the exception\nname, making it printed twice and no message at all.\n\nBefore:\n\n```\nERROR:  Loading command: install (Gem::MissingSpecVersionError)\n \tGem::MissingSpecVersionError\n```\n\nAfter:\n\n```\nERROR:  Loading command: install (Gem::MissingSpecVersionError)\n\tCould not find 'io-wait' (&gt;= 0.a) - did find: [io-wait-0.3.0-java]\n  Checked in 'GEM_PATH=/Users/deivid/Code/rubygems/rubygems/bundler/tmp/1.1/gems/system' , execute `gem env` for more information\n```\n\nhttps://github.com/rubygems/rubygems/commit/d06944bb2f","footer":"Hiroshi SHIBATA","footer_icon":"https://www.gravatar.com/avatar/f2748d34b03ed11330f2a2218904eb2d","ts":1727847295,"color":"#24282D"},
{"title":"a3929a9ca1 (master): [rubygems/rubygems] The `BUNDLER_SETUP` env should also be cleaned up","title_link":"https://github.com/ruby/ruby/commit/a3929a9ca19d69f6ab2f26d4d8ed59c2612ac733","text":"https://github.com/rubygems/rubygems/commit/47b7e50f64","footer":"Hiroshi SHIBATA","footer_icon":"https://www.gravatar.com/avatar/f2748d34b03ed11330f2a2218904eb2d","ts":1727847295,"color":"#24282D"},
{"title":"5000138084 (master): [rubygems/rubygems] Fix `bundler/inline` resetting ENV","title_link":"https://github.com/ruby/ruby/commit/50001380846c7a3a5648005b80ac8cae7fbec8f0","text":"https://github.com/rubygems/rubygems/commit/72d8d4dbba","footer":"Hiroshi SHIBATA","footer_icon":"https://www.gravatar.com/avatar/f2748d34b03ed11330f2a2218904eb2d","ts":1727847295,"color":"#24282D"},
{"title":"9d4e7b376a (master): Make spec file for env helpers more generic","title_link":"https://github.com/ruby/ruby/commit/9d4e7b376aaeeea2676ca2691cdc52996bfb3e43","text":"","footer":"Hiroshi SHIBATA","footer_icon":"https://www.gravatar.com/avatar/f2748d34b03ed11330f2a2218904eb2d","ts":1727847295,"color":"#24282D"},
{"title":"c991085176 (master): [ruby/fiddle] test: remove fragile memory leak tests","title_link":"https://github.com/ruby/ruby/commit/c99108517655db33b45edd5d74e488e2f60dfe66","text":"https://github.com/ruby/fiddle/commit/0bfcd02bef","footer":"Hiroshi SHIBATA","footer_icon":"https://www.gravatar.com/avatar/f2748d34b03ed11330f2a2218904eb2d","ts":1727847370,"color":"#24282D"},
{"title":"d2ec0e8039 (master): [ruby/fiddle] test memory-view: ensure releasing in test","title_link":"https://github.com/ruby/ruby/commit/d2ec0e8039ccb24af28570d4944db39050df817c","text":"It's for avoiding calling release on exit via GC. If it's happen, Ruby\nwill be crashed because Fiddle::MemoryView's finalizer may refer other\nRuby object. In exit phrase, the referred Ruby object may be already\nfreed.\n\nhttps://github.com/ruby/fiddle/commit/02915f13de","footer":"Hiroshi SHIBATA","footer_icon":"https://www.gravatar.com/avatar/f2748d34b03ed11330f2a2218904eb2d","ts":1727847371,"color":"#24282D"}
]}
```

**Comment by k0kubun** [comment]
http://github.com/ruby/git.ruby-lang.org/compare/b6cc44c2951ac1ac75f66888635007cb088de775...ab6497a452781139868186e01b2fa4bf730ecd9f probably fixes both of these errors.
