### ISSUE TITLE
auto-style.rb is failed with some cases

### ISSUE THREAD

**Issue by hsbt** [ruby/git.ruby-lang.org#83]
```
200 (ok), 200 (ok), 200 (ok) -- {"attachments":[{"title":"30775d0b08 (master): [DOC] Fix typo in Forwardable docs","title_link":"https://github.com/ruby/ruby/commit/30775d0b085284a6e0a54bc71025622ecabd8591","text":"","footer":"Hiroshi SHIBATA","footer_icon":"https://www.gravatar.com/avatar/f2748d34b03ed11330f2a2218904eb2d","ts":1727845980,"color":"#24282D"}]}
[221085: 2024-10-02 05:13:08 UTC] ==> commit-email.rb
master: 30775d0b08 (Nithin Bekal)
[221085: 2024-10-02 05:13:08 UTC] ==> redmine fetch changesets
[221085: 2024-10-02 05:13:08 UTC] ==> auto-style
Cloning into '/tmp/d20241002-221125-ybe7t6'...
/home/git/git.ruby-lang.org/bin/auto-style.rb:42:in `block in updated_lines': invalid byte sequence in US-ASCII (ArgumentError)

      if revs_pattern =~ line
                         ^^^^
        from /home/git/git.ruby-lang.org/bin/auto-style.rb:41:in `each'
        from /home/git/git.ruby-lang.org/bin/auto-style.rb:41:in `each_with_index'
        from /home/git/git.ruby-lang.org/bin/auto-style.rb:41:in `updated_lines'
        from /home/git/git.ruby-lang.org/bin/auto-style.rb:191:in `block (3 levels) in <main>'
        from /home/git/git.ruby-lang.org/bin/auto-style.rb:185:in `select'
        from /home/git/git.ruby-lang.org/bin/auto-style.rb:185:in `block (2 levels) in <main>'
        from /usr/local/lib/ruby/3.3.0/tmpdir.rb:99:in `mktmpdir'
        from /home/git/git.ruby-lang.org/bin/auto-style.rb:166:in `block in <main>'
        from /home/git/git.ruby-lang.org/bin/auto-style.rb:161:in `each'
        from /home/git/git.ruby-lang.org/bin/auto-style.rb:161:in `each_slice'
        from /home/git/git.ruby-lang.org/bin/auto-style.rb:161:in `each'
        from /home/git/git.ruby-lang.org/bin/auto-style.rb:161:in `map'
        from /home/git/git.ruby-lang.org/bin/auto-style.rb:161:in `<main>'
```

**Comment by hsbt** [comment]
`auto-style.rb` is now migrated to https://github.com/ruby/ruby/blob/master/tool/auto-style.rb
